name: Security check - Bandit

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Run bandit
      #uses: ioggstream/bandit-report-artifacts@v0.0.2
      uses: VCTLabs/bandit-report-artifacts@master
      with:
        project_path: pystache
        ignore_failure: true
        exclude_paths: 'pystache/tests'
